services:
  # SvelteKit App
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MINIO_ENDPOINT=${SVELTEKIT_MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - minio
    networks:
      - sveltekit-network
    env_file:
      - .env

  # MinIO (Object Storage)
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    command: server /data
    networks:
      - sveltekit-network
    env_file:
      - .env

volumes:
  minio-data:

networks:
  sveltekit-network:
    driver: bridge

