services:
  # SvelteKit App
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MINIO_ENDPOINT=${SVELTEKIT_MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - minio
      - postgres
    networks:
      - sveltekit-network
    env_file:
      - .env

  # MinIO (Object Storage)
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ENDPOINT=http://minio:9000
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data
    networks:
      - sveltekit-network
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - sveltekit-network
    restart: always
volumes:
  minio-data:
  postgres-data:

networks:
  sveltekit-network:
    driver: bridge
